CREATE TABLE `data_platform_inspection_plan_operation_data`
(
	`InspectionPlan`                            int(16) NOT NULL,
    `Operations`                                int(4) NOT NULL,
    `OperationsItem`                            int(4) NOT NULL,
    `OperationID`                               int(4) NOT NULL,
    `Inspection`                                int(6) NOT NULL,
    `OperationType`                             varchar(4) NOT NULL,
	`SupplyChainRelationshipID`                 int(16) NOT NULL,
	`SupplyChainRelationshipDeliveryID`         int(6) NOT NULL,
	`SupplyChainRelationshipDeliveryPlantID`    int(4) NOT NULL,
	`SupplyChainRelationshipProductionPlantID`  int(4) NOT NULL,
    `Product`                                  varchar(40) NOT NULL, 
    `Buyer`                                    int(12) NOT NULL,
    `Seller`                                   int(12) NOT NULL,
    `DeliverToParty`                           int(12) NOT NULL,
    `DeliverToPlant`                           varchar(4) NOT NULL,
    `DeliverFromParty`                         int(12) NOT NULL,
    `DeliverFromPlant`                         varchar(4) NOT NULL,
    `InspectionPlantBusinessPartner`           int(12) NOT NULL,
    `InspectionPlant`                          varchar(4) NOT NULL,
    `Sequence`                                 int(4) NOT NULL,
    `SequenceText`                             varchar(200) DEFAULT NULL,
    `OperationText`                            varchar(200) NOT NULL,
    `OperationStatus`                          varchar(2) DEFAULT NULL,
    `ResponsiblePlannerGroup`                  varchar(3) DEFAULT NULL,
    `OperationUnit`                            varchar(3) NOT NULL,
    `StandardLotSizeQuantity`                  float(15) DEFAULT NULL,
    `MinimumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `MaximumLotSizeQuantity`                   float(15) DEFAULT NULL,
    `PlainLongText`                            varchar(1000) DEFAULT NULL,
    `WorkCenter`                               int(16) DEFAULT NULL,
    `CapacityCategoryCode`                     varchar(3) DEFAULT NULL,
    `OperationCostingRelevancyType`            varchar(1) DEFAULT NULL,
    `OperationSetupType`                       varchar(2) DEFAULT NULL,
    `OperationSetupGroupCategory`              varchar(10) DEFAULT NULL,
    `OperationSetupGroup`                      varchar(10) DEFAULT NULL,
    `OperationReferenceQuantity`               float(15) DEFAULT NULL,
    `MaximumWaitDuration`                      float(11) DEFAULT NULL,
    `StandardWaitDuration`                     float(11) DEFAULT NULL,
    `MinimumWaitDuration`                      float(11) DEFAULT NULL,
    `WaitDurationUnit`                         varchar(3) DEFAULT NULL,
    `MaximumQueueDuration`                     float(11) DEFAULT NULL,
    `StandardQueueDuration`                    float(11) DEFAULT NULL,
    `MinimumQueueDuration`                     float(11) DEFAULT NULL,
    `QueueDurationUnit`                        varchar(3) DEFAULT NULL,
    `MaximumMoveDuration`                      float(11) DEFAULT NULL,
    `StandardMoveDuration`                     float(11) DEFAULT NULL,
    `MinimumMoveDuration`                      float(11) DEFAULT NULL,
    `MoveDurationUnit`                         varchar(3) DEFAULT NULL,
    `StandardDeliveryDuration`                 float(11) DEFAULT NULL,
    `StandardDeliveryDurationUnit`             varchar(3) DEFAULT NULL,
    `StandardOperationScrapPercent`            float(7) DEFAULT NULL,
    `CostElement`                              varchar(10) DEFAULT NULL,
    `ValidityStartDate`                        date DEFAULT NULL,
    `ValidityEndDate`                          date DEFAULT NULL,
    `CreationDate`                             date NOT NULL,
    `LastChangeDate`                           date NOT NULL,
    `IsMarkedForDeletion`                      tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`InspectionPlan`, `Operations`, `OperationsItem`, `OperationID`),
    
    CONSTRAINT `DPFMInspectionPlanOperationData_fk` FOREIGN KEY (`InspectionPlan`) REFERENCES `data_platform_inspection_plan_header_data`(`InspectionPlan`),
    CONSTRAINT `DPFMInspectionPlanOperationDataOperation_fk` FOREIGN KEY (`Operations`, `OperationsItem`, `OperationID`) REFERENCES `data_platform_operations_item_operation_data`(`Operations`, `OperationsItem`, `OperationID`),
    CONSTRAINT `DPFMInspectionPlanOperationDataInspection_fk` FOREIGN KEY (`InspectionPlan`, `Inspection`) REFERENCES `data_platform_inspection_plan_inspection_data`(`InspectionPlan`, `Inspection`),
    CONSTRAINT `DPFMInspectionPlanOperationDataSCRID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `Buyer`, `Seller`) REFERENCES `data_platform_scr_general_data` (`SupplyChainRelationshipID`, `Buyer`, `Seller`),
    CONSTRAINT `DPFMInspectionPlanOperationDataSCRDeliveryID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`) REFERENCES `data_platform_scr_delivery_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`),
    CONSTRAINT `DPFMInspectionPlanOperationDataSCRDeliveryPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`) REFERENCES `data_platform_scr_delivery_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipDeliveryID`, `SupplyChainRelationshipDeliveryPlantID`, `Buyer`, `Seller`, `DeliverToParty`, `DeliverFromParty`, `DeliverToPlant`, `DeliverFromPlant`, `Product`),
    CONSTRAINT `DPFMInspectionPlanOperationDataSCRProductionPlantIDProduct_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`) REFERENCES `data_platform_scr_production_plant_relation_product_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipProductionPlantID`, `Buyer`, `Seller`, `ProductionPlantBusinessPartner`, `ProductionPlant`, `Product`),
    CONSTRAINT `DPFMInspectionPlanOperationDataOperationUnit_fk` FOREIGN KEY (`OperationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionPlanOperationDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_general_data` (`WorkCenter`),
    CONSTRAINT `DPFMInspectionPlanOperationDataWaitDurationUnit_fk` FOREIGN KEY (`WaitDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionPlanOperationDataQueueDurationUnit_fk` FOREIGN KEY (`QueueDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionPlanOperationDataMoveDurationUnit_fk` FOREIGN KEY (`MoveDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMInspectionPlanOperationDataStandardDeliveryDurationUnit_fk` FOREIGN KEY (`StandardDeliveryDurationUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`)
    
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
